# database generated on 2023-08-11 12:55 GMT
!!omap
- /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/vm_RWX_Access_S_01.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv32
- /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/vm_RWX_Access_S_02.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv32
- /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/vm_RWX_Access_S_03.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv32
- /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/vm_RWX_Access_S_04.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv32
- /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/vm_RWX_Access_S_05.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv32
- /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/vm_RWX_Access_S_06.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv32
- /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/vm_RWX_Access_S_07.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv32
- /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/vm_RWX_Access_S_08.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv32
- /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/vm_RWX_Access_S_09.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv32
- /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/vm_RWX_Access_S_10.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv32
- /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/vm_RWX_Access_S_11.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv32
- /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/vm_RWX_Access_S_12.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv32
