# database generated on 2023-09-20 09:12 GMT
!!omap
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/Valid_bit_tests/check.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/Valid_bit_tests/invalid_pte_level0.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/Valid_bit_tests/invalid_pte_level0_1.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/Valid_bit_tests/invalid_pte_level0_x_s.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/Valid_bit_tests/invalid_pte_level0_x_s_1.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/Valid_bit_tests/invalid_pte_level1.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/Valid_bit_tests/invalid_pte_level1_1.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/Valid_bit_tests/invalid_pte_level1_x_s.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/Valid_bit_tests/invalid_pte_level1_x_s_1.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/Valid_bit_tests/invalid_pte_level2.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/Valid_bit_tests/invalid_pte_level2_1.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/Valid_bit_tests/invalid_pte_level2_x_s.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/Valid_bit_tests/invalid_pte_level2_x_s_1.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/Valid_bit_tests/invalid_pte_level3.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/Valid_bit_tests/invalid_pte_level3_1.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/Valid_bit_tests/invalid_pte_level3_x_s.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/Valid_bit_tests/invalid_pte_level3_x_s_1.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
