# database generated on 2023-09-22 08:52 GMT
!!omap
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/non_leaf_pte_tests/non_leaf_pte_01.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/non_leaf_pte_tests/non_leaf_pte_02.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/non_leaf_pte_tests/non_leaf_pte_03.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/non_leaf_pte_tests/non_leaf_pte_04.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/non_leaf_pte_tests/non_leaf_pte_05.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/non_leaf_pte_tests/non_leaf_pte_06.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/non_leaf_pte_tests/non_leaf_pte_07.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/non_leaf_pte_tests/non_leaf_pte_08.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/non_leaf_pte_tests/non_leaf_pte_09.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/non_leaf_pte_tests/non_leaf_pte_10.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/non_leaf_pte_tests/non_leaf_pte_11.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/hamza/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv48_tests/non_leaf_pte_tests/non_leaf_pte_12.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
