# database generated on 2023-08-10 10:40 GMT
!!omap
- /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/satp_access_permission.S:
    commit_id: '-'
    isa:
    - RV32I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv32
