# database generated on 2023-09-19 08:11 GMT
!!omap
- /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv39_tests/check.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv39_tests/invalid_pte_level0.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv39_tests/invalid_pte_level1.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
- /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv64i_m/vm_sv39_tests/invalid_pte_level2.S:
    commit_id: '-'
    isa:
    - RV64I_Zicsr
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*64.*)
        - check ISA:=regex(.*I.*Zicsr.*)
        define:
        - def rvtest_mtrap_routine=True
        - def rvtest_strap_routine=True
        - def TEST_CASE_1=True
        coverage_labels:
        - sv64
