

.PHONY : TARGET0
TARGET0 :
	@cd /home/ammar/Documents/riscv-arch-test/riscof_work/vm_invalid_pte_01.S/dut; riscv32-unknown-elf-gcc -march=rv32i_zicsr          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/ammar/Documents/riscv-arch-test/spike/env/link.ld         -I /home/ammar/Documents/riscv-arch-test/spike/env/         -I /home/ammar/Documents/riscv-arch-test/riscv-test-suite/env /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/vm_invalid_pte_01.S -o my.elf  -Drvtest_mtrap_routine=True -Drvtest_strap_routine=True -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; spike --isa=rv32imc +signature=/home/ammar/Documents/riscv-arch-test/riscof_work/vm_invalid_pte_01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET1
TARGET1 :
	@cd /home/ammar/Documents/riscv-arch-test/riscof_work/vm_invalid_pte_02.S/dut; riscv32-unknown-elf-gcc -march=rv32i_zicsr          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/ammar/Documents/riscv-arch-test/spike/env/link.ld         -I /home/ammar/Documents/riscv-arch-test/spike/env/         -I /home/ammar/Documents/riscv-arch-test/riscv-test-suite/env /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/vm_invalid_pte_02.S -o my.elf  -Drvtest_mtrap_routine=True -Drvtest_strap_routine=True -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; spike --isa=rv32imc +signature=/home/ammar/Documents/riscv-arch-test/riscof_work/vm_invalid_pte_02.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET2
TARGET2 :
	@cd /home/ammar/Documents/riscv-arch-test/riscof_work/vm_invalid_pte_03.S/dut; riscv32-unknown-elf-gcc -march=rv32i_zicsr          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/ammar/Documents/riscv-arch-test/spike/env/link.ld         -I /home/ammar/Documents/riscv-arch-test/spike/env/         -I /home/ammar/Documents/riscv-arch-test/riscv-test-suite/env /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/vm_invalid_pte_03.S -o my.elf  -Drvtest_mtrap_routine=True -Drvtest_strap_routine=True -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; spike --isa=rv32imc +signature=/home/ammar/Documents/riscv-arch-test/riscof_work/vm_invalid_pte_03.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET3
TARGET3 :
	@cd /home/ammar/Documents/riscv-arch-test/riscof_work/vm_invalid_pte_04.S/dut; riscv32-unknown-elf-gcc -march=rv32i_zicsr          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/ammar/Documents/riscv-arch-test/spike/env/link.ld         -I /home/ammar/Documents/riscv-arch-test/spike/env/         -I /home/ammar/Documents/riscv-arch-test/riscv-test-suite/env /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/vm_invalid_pte_04.S -o my.elf  -Drvtest_mtrap_routine=True -Drvtest_strap_routine=True -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; spike --isa=rv32imc +signature=/home/ammar/Documents/riscv-arch-test/riscof_work/vm_invalid_pte_04.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET4
TARGET4 :
	@cd /home/ammar/Documents/riscv-arch-test/riscof_work/vm_invalid_pte_05.S/dut; riscv32-unknown-elf-gcc -march=rv32i_zicsr          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/ammar/Documents/riscv-arch-test/spike/env/link.ld         -I /home/ammar/Documents/riscv-arch-test/spike/env/         -I /home/ammar/Documents/riscv-arch-test/riscv-test-suite/env /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/vm_invalid_pte_05.S -o my.elf  -Drvtest_mtrap_routine=True -Drvtest_strap_routine=True -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; spike --isa=rv32imc +signature=/home/ammar/Documents/riscv-arch-test/riscof_work/vm_invalid_pte_05.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET5
TARGET5 :
	@cd /home/ammar/Documents/riscv-arch-test/riscof_work/vm_invalid_pte_06.S/dut; riscv32-unknown-elf-gcc -march=rv32i_zicsr          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/ammar/Documents/riscv-arch-test/spike/env/link.ld         -I /home/ammar/Documents/riscv-arch-test/spike/env/         -I /home/ammar/Documents/riscv-arch-test/riscv-test-suite/env /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/vm_invalid_pte_06.S -o my.elf  -Drvtest_mtrap_routine=True -Drvtest_strap_routine=True -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; spike --isa=rv32imc +signature=/home/ammar/Documents/riscv-arch-test/riscof_work/vm_invalid_pte_06.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET6
TARGET6 :
	@cd /home/ammar/Documents/riscv-arch-test/riscof_work/vm_invalid_pte_07.S/dut; riscv32-unknown-elf-gcc -march=rv32i_zicsr          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/ammar/Documents/riscv-arch-test/spike/env/link.ld         -I /home/ammar/Documents/riscv-arch-test/spike/env/         -I /home/ammar/Documents/riscv-arch-test/riscv-test-suite/env /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/vm_invalid_pte_07.S -o my.elf  -Drvtest_mtrap_routine=True -Drvtest_strap_routine=True -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; spike --isa=rv32imc +signature=/home/ammar/Documents/riscv-arch-test/riscof_work/vm_invalid_pte_07.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET7
TARGET7 :
	@cd /home/ammar/Documents/riscv-arch-test/riscof_work/vm_invalid_pte_08.S/dut; riscv32-unknown-elf-gcc -march=rv32i_zicsr          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/ammar/Documents/riscv-arch-test/spike/env/link.ld         -I /home/ammar/Documents/riscv-arch-test/spike/env/         -I /home/ammar/Documents/riscv-arch-test/riscv-test-suite/env /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/vm_invalid_pte_08.S -o my.elf  -Drvtest_mtrap_routine=True -Drvtest_strap_routine=True -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; spike --isa=rv32imc +signature=/home/ammar/Documents/riscv-arch-test/riscof_work/vm_invalid_pte_08.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET8
TARGET8 :
	@cd /home/ammar/Documents/riscv-arch-test/riscof_work/vm_invalid_pte_09.S/dut; riscv32-unknown-elf-gcc -march=rv32i_zicsr          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/ammar/Documents/riscv-arch-test/spike/env/link.ld         -I /home/ammar/Documents/riscv-arch-test/spike/env/         -I /home/ammar/Documents/riscv-arch-test/riscv-test-suite/env /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/vm_invalid_pte_09.S -o my.elf  -Drvtest_mtrap_routine=True -Drvtest_strap_routine=True -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; spike --isa=rv32imc +signature=/home/ammar/Documents/riscv-arch-test/riscof_work/vm_invalid_pte_09.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET9
TARGET9 :
	@cd /home/ammar/Documents/riscv-arch-test/riscof_work/vm_invalid_pte_10.S/dut; riscv32-unknown-elf-gcc -march=rv32i_zicsr          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/ammar/Documents/riscv-arch-test/spike/env/link.ld         -I /home/ammar/Documents/riscv-arch-test/spike/env/         -I /home/ammar/Documents/riscv-arch-test/riscv-test-suite/env /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/vm_invalid_pte_10.S -o my.elf  -Drvtest_mtrap_routine=True -Drvtest_strap_routine=True -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; spike --isa=rv32imc +signature=/home/ammar/Documents/riscv-arch-test/riscof_work/vm_invalid_pte_10.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET10
TARGET10 :
	@cd /home/ammar/Documents/riscv-arch-test/riscof_work/vm_invalid_pte_11.S/dut; riscv32-unknown-elf-gcc -march=rv32i_zicsr          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/ammar/Documents/riscv-arch-test/spike/env/link.ld         -I /home/ammar/Documents/riscv-arch-test/spike/env/         -I /home/ammar/Documents/riscv-arch-test/riscv-test-suite/env /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/vm_invalid_pte_11.S -o my.elf  -Drvtest_mtrap_routine=True -Drvtest_strap_routine=True -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; spike --isa=rv32imc +signature=/home/ammar/Documents/riscv-arch-test/riscof_work/vm_invalid_pte_11.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET11
TARGET11 :
	@cd /home/ammar/Documents/riscv-arch-test/riscof_work/vm_invalid_pte_12.S/dut; riscv32-unknown-elf-gcc -march=rv32i_zicsr          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/ammar/Documents/riscv-arch-test/spike/env/link.ld         -I /home/ammar/Documents/riscv-arch-test/spike/env/         -I /home/ammar/Documents/riscv-arch-test/riscv-test-suite/env /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/vm_invalid_pte_12.S -o my.elf  -Drvtest_mtrap_routine=True -Drvtest_strap_routine=True -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; spike --isa=rv32imc +signature=/home/ammar/Documents/riscv-arch-test/riscof_work/vm_invalid_pte_12.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;