

.PHONY : TARGET0
TARGET0 :
	@cd /home/ammar/Documents/riscv-arch-test/riscof_work/vm_SATP_access.S/dut; riscv32-unknown-elf-gcc -march=rv32i_zicsr          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/ammar/Documents/riscv-arch-test/spike/env/link.ld         -I /home/ammar/Documents/riscv-arch-test/spike/env/         -I /home/ammar/Documents/riscv-arch-test/riscv-test-suite/env /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/vm_SATP_access.S -o my.elf  -Drvtest_mtrap_routine=True -Drvtest_strap_routine=True -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; spike --isa=rv32imc +signature=/home/ammar/Documents/riscv-arch-test/riscof_work/vm_SATP_access.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET1
TARGET1 :
	@cd /home/ammar/Documents/riscv-arch-test/riscof_work/vm_invalid_PTE_01.S/dut; riscv32-unknown-elf-gcc -march=rv32i_zicsr          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/ammar/Documents/riscv-arch-test/spike/env/link.ld         -I /home/ammar/Documents/riscv-arch-test/spike/env/         -I /home/ammar/Documents/riscv-arch-test/riscv-test-suite/env /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/vm_test/check/vm_invalid_PTE_01.S -o my.elf  -Drvtest_mtrap_routine=True -Drvtest_strap_routine=True -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; spike --isa=rv32imc +signature=/home/ammar/Documents/riscv-arch-test/riscof_work/vm_invalid_PTE_01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;