

.PHONY : TARGET0
TARGET0 :
	@cd /home/ammar/Documents/riscv-arch-test/riscof_work/src/div-01.S/dut; riscv32-unknown-elf-gcc -march=rv32im          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/ammar/Documents/riscv-arch-test/spike/env/link.ld         -I /home/ammar/Documents/riscv-arch-test/spike/env/         -I /home/ammar/Documents/riscv-arch-test/riscv-test-suite/env /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/M/src/div-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; spike --isa=rv32imc +signature=/home/ammar/Documents/riscv-arch-test/riscof_work/src/div-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET1
TARGET1 :
	@cd /home/ammar/Documents/riscv-arch-test/riscof_work/src/divu-01.S/dut; riscv32-unknown-elf-gcc -march=rv32im          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/ammar/Documents/riscv-arch-test/spike/env/link.ld         -I /home/ammar/Documents/riscv-arch-test/spike/env/         -I /home/ammar/Documents/riscv-arch-test/riscv-test-suite/env /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/M/src/divu-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; spike --isa=rv32imc +signature=/home/ammar/Documents/riscv-arch-test/riscof_work/src/divu-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET2
TARGET2 :
	@cd /home/ammar/Documents/riscv-arch-test/riscof_work/src/mul-01.S/dut; riscv32-unknown-elf-gcc -march=rv32im          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/ammar/Documents/riscv-arch-test/spike/env/link.ld         -I /home/ammar/Documents/riscv-arch-test/spike/env/         -I /home/ammar/Documents/riscv-arch-test/riscv-test-suite/env /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/M/src/mul-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; spike --isa=rv32imc +signature=/home/ammar/Documents/riscv-arch-test/riscof_work/src/mul-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET3
TARGET3 :
	@cd /home/ammar/Documents/riscv-arch-test/riscof_work/src/mulh-01.S/dut; riscv32-unknown-elf-gcc -march=rv32im          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/ammar/Documents/riscv-arch-test/spike/env/link.ld         -I /home/ammar/Documents/riscv-arch-test/spike/env/         -I /home/ammar/Documents/riscv-arch-test/riscv-test-suite/env /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/M/src/mulh-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; spike --isa=rv32imc +signature=/home/ammar/Documents/riscv-arch-test/riscof_work/src/mulh-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET4
TARGET4 :
	@cd /home/ammar/Documents/riscv-arch-test/riscof_work/src/mulhsu-01.S/dut; riscv32-unknown-elf-gcc -march=rv32im          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/ammar/Documents/riscv-arch-test/spike/env/link.ld         -I /home/ammar/Documents/riscv-arch-test/spike/env/         -I /home/ammar/Documents/riscv-arch-test/riscv-test-suite/env /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/M/src/mulhsu-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; spike --isa=rv32imc +signature=/home/ammar/Documents/riscv-arch-test/riscof_work/src/mulhsu-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET5
TARGET5 :
	@cd /home/ammar/Documents/riscv-arch-test/riscof_work/src/mulhu-01.S/dut; riscv32-unknown-elf-gcc -march=rv32im          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/ammar/Documents/riscv-arch-test/spike/env/link.ld         -I /home/ammar/Documents/riscv-arch-test/spike/env/         -I /home/ammar/Documents/riscv-arch-test/riscv-test-suite/env /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/M/src/mulhu-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; spike --isa=rv32imc +signature=/home/ammar/Documents/riscv-arch-test/riscof_work/src/mulhu-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET6
TARGET6 :
	@cd /home/ammar/Documents/riscv-arch-test/riscof_work/src/rem-01.S/dut; riscv32-unknown-elf-gcc -march=rv32im          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/ammar/Documents/riscv-arch-test/spike/env/link.ld         -I /home/ammar/Documents/riscv-arch-test/spike/env/         -I /home/ammar/Documents/riscv-arch-test/riscv-test-suite/env /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/M/src/rem-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; spike --isa=rv32imc +signature=/home/ammar/Documents/riscv-arch-test/riscof_work/src/rem-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;

.PHONY : TARGET7
TARGET7 :
	@cd /home/ammar/Documents/riscv-arch-test/riscof_work/src/remu-01.S/dut; riscv32-unknown-elf-gcc -march=rv32im          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/ammar/Documents/riscv-arch-test/spike/env/link.ld         -I /home/ammar/Documents/riscv-arch-test/spike/env/         -I /home/ammar/Documents/riscv-arch-test/riscv-test-suite/env /home/ammar/Documents/riscv-arch-test/riscv-test-suite/rv32i_m/M/src/remu-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; spike --isa=rv32imc +signature=/home/ammar/Documents/riscv-arch-test/riscof_work/src/remu-01.S/dut/DUT-spike.signature +signature-granularity=4 my.elf;